### ISSUE TITLE
ChaCha20 ?

### ISSUE THREAD

**Issue by ysbaddaden** [konovod/prngs#1]
You appealed to me with those quick PRNG implementations. I'd love to see Chacha20 too, now :-)

**Comment by konovod** [comment]
Chacha20 as a PRNG will be perhaps much slower then even MT. Even Chacha8 is slow. Of course it should be tested.
As a symmetric cipher it's awesome though, but i'm not sure if it's needed in standard library, because direct usage is wrong, there should be libsodium-like high-level interface.

**Comment by ysbaddaden** [comment]
I didn't expect it to be that slow. I know its mostly used for encryptions (ChaCha20-Poly1305 variant), but OpenBSD uses ChaCha20 in its [arc4random implementation](https://github.com/openbsd/src/blob/master/lib/libc/crypt/arc4random.c), so I wondered how it would perform.

**Comment by konovod** [comment]
AFAIK it's used in CSPRNG because it's well, impossible to predict, and that's main requirement for system random, so performance is worse then general PRNGs.
Here is quick and dirty implementation on carc.in: https://carc.in/#/r/247g 
`4.times` instead of `10.times` will make it ChaCha8, but it's still slow.
i don't have an access to linux for now, but i doubt release mode or initialization tweaks will change much. There is also C++ SIMD-version that use smaller buffer: https://gist.github.com/orlp/32f5d1b631ab092608b1 but i have no idea how to convert it to crystal and according to pcg-random.org it's still slow.

**Comment by ysbaddaden** [comment]
Wow, thanks!

**Comment by konovod** [comment]
Huh, my implementation is totally wrong, right one is twice slower because only half of the buffer can be used for random generation.

**Comment by konovod** [comment]
Actually, i've fixed ChaCha20, and it seems to be so slow only in debug mode, and in release it is as fast as MT, at least on my machine.

**Comment by ysbaddaden** [comment]
Great results! LLVM optimizations are doing great. PCG32 is still a faster solution for general purpose, even in both release and non-release mode, but ChaCha20 could be useful in some scenarios, as ISAAC can be, but with less memory, if I understand correctly.
